apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/metrics'
    prometheus.io/port: backendport
  labels:
    monitoring: 'true'
    release: prometheus
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - env:
        - name: JAEGER_HOST
          value: simplest.observability.svc.cluster.local
        name: backend
        image: mivodu/backend-project-3:v0.2.0
        ports:
        - name: backendport
          containerPort: 8080
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    monitoring: 'true'
    release: prometheus
    app: backend
spec:
  selector:
    app: backend
  ports:
    - name: backend
      protocol: TCP
      port: 8081
      targetPort: backendport
  type: LoadBalancer
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-monitor
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/metrics'
    prometheus.io/port: backendport
  namespace: monitoring
  labels:
    app: backend
    release: prometheus
spec:
  selector:
    matchLabels:
      app: backend
  endpoints:
  - port: backend
    path: /metrics
    targetPort: backendport
    interval: 15s
  jobLabel: monitoring-backend
  namespaceSelector:
    matchNames:
    - default
