apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/metrics'
    prometheus.io/port: frontendport
  labels:
    monitoring: 'true'
    release: prometheus
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: mivodu/frontend-project-3:v0.1.0
        ports:
        - name: frontendport
          containerPort: 8080
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    monitoring: 'true'
    release: prometheus
    app: frontend
spec:
  selector:
    app: frontend
  ports:
    - name: frontend
      port: 8080
      targetPort: frontendport
      protocol: TCP
  type: LoadBalancer
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: frontend-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  endpoints:
  - port: frontend
    targetPort: frontendport
    interval: 15s
    path: /metrics
  jobLabel: monitoring-frontend
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      app: frontend